name: yuktidea_assessment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^0.13.6
  json_annotation: ^4.8.1
  flutter_widget_from_html: ^0.14.11
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9  
  sliding_up_panel: ^2.0.0+1
  intl: ^0.18.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

